export const PAINT = 'PAINT'
export const SELL = 'SELL'
export const STUDIOUPDATE = 'STUDIOUPDATE'
export const HIRING = 'HIRING'
export const AUTOSELL = 'AUTOSELL'
export const CHANGEBLOCK = 'CHANGEBLOCK'
export const GALLERYWORKING = 'GALLERYWORKING'
